import { TailwindIndicator } from "@/components/utils/tailwind-indicator";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


// Font files to be colocated inside app

const satoshi = localFont({
  src: /*"@app/satoshi/Satoshi-Light.oft", */"./satoshi/Satoshi-Light.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
